---
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - run: pip install pyinstaller
      - run: pyinstaller -F --noupx tcpscan.py
      # verify that it works
      - run: ./dist/tcp-scan/tcp-scan --help
      - uses: actions/upload-artifact@v4
        with:
          path: dist/*
